---

#- name: Change file persmissions for NSCA
#  file: path={{ item.path }}
#        state=directory
#        mode={{ item.mode }}
#  with_items:
#      - { path: '/var/lib/nagios3/rw', mode: 2710 }
#      - { path: '/var/lib/nagios3', mode: 751 }

- name: Configure NSCA
  lineinfile:
    dest: "{{ nsca_config_file }}"
    regexp: '^#?{{ item.option }}'
    line: '{{ item.option }}={{ item.value }}'
    state: "{{ item.state|default('present') }}"
    backup: yes
  with_items: "{{ nsca_config_options }}"
  notify: Reload NSCA
