---

- name: Configure Icinga CGI
  lineinfile:
    dest: "{{ icinga_cgi_file }}"
    regexp: '^#?{{ item.option }}'
    line: '{{ item.option }}={{ item.value }}'
    state: "{{ item.state|default('present') }}"
    backup: yes
  with_items: "{{ icinga_cgi_options }}"
  notify: Reload Icinga
