---

- name: Install Icinga
  apt:  pkg={{ item }}
        state=installed
        update_cache={{ icinga_apt_update_cache }}
        cache_valid_time={{ icinga_apt_cache_valid_time }}
  with_items: "{{ icinga_apt_dependencies }}"
