# file: nagios-server/handlers/main.yml

- name: Reconfigure icinga-common
  command: dpkg-reconfigure -f noninteractive icinga-common

- name: Reload Icinga
  service:
    name: "{{ icinga_service }}"
    state: reloaded

- name: Reload NSCA
  service:
    name: "{{ nsca_service }}"
    state: reloaded

- name: Restart Apache
  service: name=apache2 state=restarted
  when: icinga_a2_config

- name: Reload Apache
  service: name=apache2 state=reloaded
  when: icinga_a2_config
